name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    标签:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: 获取依赖
        run: flutter pub get
        working-directory: ./simple_live_app

      - name: 编译 Windows
        run: flutter build windows --release
        working-directory: ./simple_live_app

      - name: 打包到根目录
        run: |
          cd simple_live_app\build\windows\x64\runner\Release
          powershell Compress-Archive -Path * -DestinationPath "$env:GITHUB_WORKSPACE\XiaoYa_Live_Windows_Latest.zip" -Force

      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: XiaoYa_Live_Windows_Latest
          path: XiaoYa_Live_Windows_Latest.zip
